#!/bin/sh
set -e

# Eski sürümden (linamp) kalan dizin ve menü dosyalarını temizle
if [ -d "/usr/share/linamp" ]; then
    rm -rf /usr/share/linamp
fi

if [ -f "/usr/share/applications/linamp.desktop" ]; then
    rm -f /usr/share/applications/linamp.desktop
fi

if [ -f "/usr/share/pixmaps/linamp.png" ]; then
    rm -f /usr/share/pixmaps/linamp.png
fi

exit 0
